const RESTAURANT_DATA = {
    "statusCode": 0,
    "data": {
        "cacheExpiryTime": 320, "pages": 1, "pageIndex": 0, "scrubber": 0, "filters": [{
            "type": "FilterWidget",
            "title": "Cuisines",
            "key": "CUISINES",
            "configType": "checkbox",
            "visible": 1,
            "options": [{
                "option": "Afghani", "selected": 0, "visible": 1,
            }, {
                "option": "American", "selected": 0, "visible": 1,
            }, {
                "option": "Asian", "selected": 0, "visible": 1,
            }, {
                "option": "Bakery", "selected": 0, "visible": 1,
            }, {
                "option": "Barbecue", "selected": 0, "visible": 1,
            }, {
                "option": "Bengali", "selected": 0, "visible": 1,
            }, {
                "option": "Beverages", "selected": 0, "visible": 1,
            }, {
                "option": "Biryani", "selected": 0, "visible": 1,
            }, {
                "option": "Burgers", "selected": 0, "visible": 1,
            }, {
                "option": "Burmese", "selected": 0, "visible": 1,
            }, {
                "option": "Cafe", "selected": 0, "visible": 1,
            }, {
                "option": "Chaat", "selected": 0, "visible": 1,
            }, {
                "option": "Chinese", "selected": 0, "visible": 1,
            }, {
                "option": "Combo", "selected": 0, "visible": 1,
            }, {
                "option": "Continental", "selected": 0, "visible": 1,
            }, {
                "option": "Desserts", "selected": 0, "visible": 1,
            }, {
                "option": "Fast Food", "selected": 0, "visible": 1,
            }, {
                "option": "Grill", "selected": 0, "visible": 1,
            }, {
                "option": "Gujarati", "selected": 0, "visible": 1,
            }, {
                "option": "Healthy Food", "selected": 0, "visible": 1,
            }, {
                "option": "Home Food", "selected": 0, "visible": 1,
            }, {
                "option": "Hyderabadi", "selected": 0, "visible": 1,
            }, {
                "option": "Ice Cream", "selected": 0, "visible": 1,
            }, {
                "option": "Ice Cream Cakes", "selected": 0, "visible": 1,
            }, {
                "option": "Indian", "selected": 0, "visible": 1,
            }, {
                "option": "Italian", "selected": 0, "visible": 1,
            }, {
                "option": "Italian-American", "selected": 0, "visible": 1,
            }, {
                "option": "Jain", "selected": 0, "visible": 1,
            }, {
                "option": "Japanese", "selected": 0, "visible": 1,
            }, {
                "option": "Juices", "selected": 0, "visible": 1,
            }, {
                "option": "Kebabs", "selected": 0, "visible": 1,
            }, {
                "option": "Kerala", "selected": 0, "visible": 1,
            }, {
                "option": "Keto", "selected": 0, "visible": 1,
            }, {
                "option": "Lebanese", "selected": 0, "visible": 1,
            }, {
                "option": "Lucknowi", "selected": 0, "visible": 1,
            }, {
                "option": "Maharashtrian", "selected": 0, "visible": 1,
            }, {
                "option": "Mediterranean", "selected": 0, "visible": 1,
            }, {
                "option": "Mexican", "selected": 0, "visible": 1,
            }, {
                "option": "Middle Eastern", "selected": 0, "visible": 1,
            }, {
                "option": "Mughlai", "selected": 0, "visible": 1,
            }, {
                "option": "Nepalese", "selected": 0, "visible": 1,
            }, {
                "option": "North Indian", "selected": 0, "visible": 1,
            }, {
                "option": "Oriental", "selected": 0, "visible": 1,
            }, {
                "option": "Oriya", "selected": 0, "visible": 1,
            }, {
                "option": "Paan", "selected": 0, "visible": 1,
            }, {
                "option": "Pan-Asian", "selected": 0, "visible": 1,
            }, {
                "option": "Pastas", "selected": 0, "visible": 1,
            }, {
                "option": "Persian", "selected": 0, "visible": 1,
            }, {
                "option": "Pizzas", "selected": 0, "visible": 1,
            }, {
                "option": "Punjabi", "selected": 0, "visible": 1,
            }, {
                "option": "Rajasthani", "selected": 0, "visible": 1,
            }, {
                "option": "Salads", "selected": 0, "visible": 1,
            }, {
                "option": "Seafood", "selected": 0, "visible": 1,
            }, {
                "option": "Snacks", "selected": 0, "visible": 1,
            }, {
                "option": "South Indian", "selected": 0, "visible": 1,
            }, {
                "option": "Street Food", "selected": 0, "visible": 1,
            }, {
                "option": "Sushi", "selected": 0, "visible": 1,
            }, {
                "option": "Sweets", "selected": 0, "visible": 1,
            }, {
                "option": "Tandoor", "selected": 0, "visible": 1,
            }, {
                "option": "Thai", "selected": 0, "visible": 1,
            }, {
                "option": "Thalis", "selected": 0, "visible": 1,
            }, {
                "option": "Waffle", "selected": 0, "visible": 1,
            },],
            "detail": "",
            "heading": "Cuisines",
            "applicable": 1,
            "searchable": 1,
        }, {
            "type": "FilterWidget",
            "title": "Show Restaurants With",
            "key": "SHOW_RESTAURANTS_WITH",
            "configType": "checkbox",
            "visible": 1,
            "options": [{
                "option": "Offers", "selected": 0, "visible": 1,
            }, {
                "option": "Pure Veg", "selected": 0, "visible": 1,
            },],
            "detail": "",
            "heading": "Offers & More",
            "applicable": 1,
            "searchable": 0,
        },], "sorts": [{
            "type": "SortWidget",
            "key": "RELEVANCE",
            "title": "Relevance",
            "selected": 1,
            "visible": 1,
            "defaultSelection": true,
        }, {
            "type": "SortWidget",
            "key": "DELIVERY_TIME",
            "title": "Delivery Time",
            "selected": 0,
            "visible": 1,
            "defaultSelection": false,
        }, {
            "type": "SortWidget",
            "key": "RATING",
            "title": "Rating",
            "selected": 0,
            "visible": 1,
            "defaultSelection": false,
        }, {
            "type": "SortWidget",
            "key": "COST_FOR_TWO",
            "title": "Cost: Low to High",
            "selected": 0,
            "visible": 1,
            "defaultSelection": false,
        }, {
            "type": "SortWidget",
            "key": "COST_FOR_TWO_H2L",
            "title": "Cost: High to Low",
            "selected": 0,
            "visible": 1,
            "defaultSelection": false,
        },], "configs": {
            "ribbons": {
                "PREORDER": {
                    "type": "PREORDER",
                    "text": "Preorder",
                    "textColor": "#ffffff",
                    "imageId": "sfefefefeegeg",
                    "topBackgroundColor": "#d53d4c",
                    "bottomBackgroundColor": "#af2330",
                    "priority": 3,
                }, "EXCLUSIVE": {
                    "type": "EXCLUSIVE",
                    "text": "Exclusive",
                    "textColor": "#ffffff",
                    "imageId": "sfefefefeegeg",
                    "topBackgroundColor": "#fa4a5b",
                    "bottomBackgroundColor": "#d12a3b",
                    "priority": 2,
                }, "NEW": {
                    "type": "NEW",
                    "text": "Newly Added",
                    "textColor": "#ffffff",
                    "imageId": "sfefefefeegeg",
                    "topBackgroundColor": "#d53d4c",
                    "bottomBackgroundColor": "#af2330",
                    "priority": 4,
                }, "REPEAT": {
                    "type": "REPEAT",
                    "text": "Repeat",
                    "textColor": "#ffffff",
                    "imageId": "sfefefefeegeg",
                    "topBackgroundColor": "#D53D4C",
                    "bottomBackgroundColor": "#B02331",
                    "priority": 6,
                }, "CLOUD": {
                    "type": "CLOUD",
                    "text": "Daily Menus",
                    "textColor": "#ffffff",
                    "imageId": "sfefefefeegeg",
                    "topBackgroundColor": "#fa4a5b",
                    "bottomBackgroundColor": "#d12a3b",
                    "priority": 5,
                }, "PREMIUM": {
                    "type": "PREMIUM",
                    "text": "Premium",
                    "textColor": "#ffffff",
                    "imageId": "sfefefefeegeg",
                    "topBackgroundColor": "#8a584b",
                    "bottomBackgroundColor": "#583229",
                    "priority": 7,
                }, "PROMOTED": {
                    "type": "PROMOTED",
                    "text": "Promoted",
                    "textColor": "#ffffff",
                    "imageId": "sfefefefeegeg",
                    "topBackgroundColor": "#3a3c41",
                    "bottomBackgroundColor": "#1e2023",
                    "priority": 1,
                },
            }, "croutons": {
                "RAIN": {
                    "type": "Crouton",
                    "bgColor": "#282C3F",
                    "icon": "surge_listing_piuzrv",
                    "textColor": "#ffffff",
                    "title": "Bad Weather",
                    "message": "${amount} extra levied on some restaurants",
                }, "RAIN_DEFAULT": {
                    "type": "Crouton",
                    "bgColor": "#282C3F",
                    "icon": "surge_listing_piuzrv",
                    "textColor": "#ffffff",
                    "title": "Bad Weather",
                    "message": "Your orders may be delayed by 5-10 mins",
                }, "SERVICEABLE_WITH_BANNER_RAIN": {
                    "type": "Crouton",
                    "bgColor": "#282C3F",
                    "icon": "rain_crouton_4x",
                    "textColor": "#ffffff",
                    "title": "Bad Weather",
                    "message": "Few restaurants unserviceable due to rains",
                }, "RAIN_LOW": {
                    "type": "Crouton",
                    "bgColor": "#282C3F",
                    "icon": "surge_listing_piuzrv",
                    "textColor": "#ffffff",
                    "title": "Bad Weather",
                    "message": "Your orders may be delayed by 5-10 mins",
                }, "RAIN_HIGH": {
                    "type": "Crouton",
                    "bgColor": "#282C3F",
                    "icon": "surge_listing_piuzrv",
                    "textColor": "#ffffff",
                    "title": "Bad Weather",
                    "message": "Your orders may be delayed by 5-10 mins",
                }, "SPECIAL": {
                    "type": "Crouton",
                    "bgColor": "#282C3F",
                    "icon": "surge_listing_piuzrv",
                    "textColor": "#ffffff",
                    "title": "High Demand",
                    "message": "Surge fee of Rs ${amount} may be applicable",
                },
            },
        }, "cards": [{
            "cardType": "carousel", "layoutAlignmentType": "VERTICAL", "data": {
                "type": "carousel", "subtype": "topCarousel", "data": {
                    "cards": [{
                        "type": "carouselElement", "subtype": "image", "data": {
                            "bannerId": 635529,
                            "creativeId": "rng/md/carousel/production/pneknawbadtvceqzwiep",
                            "type": "restaurantCollectionV2",
                            "link": "49301",
                            "cityId": 0,
                            "restaurantUuid": "",
                            "restaurantParentId": "0",
                            "thirdPartyVendor": "",
                            "thirdPartyAddress": false,
                        },
                    }, {
                        "type": "carouselElement", "subtype": "image", "data": {
                            "bannerId": 304993,
                            "creativeId": "rng/md/carousel/production/lori508m4xps01tnywxf",
                            "type": "restaurantCollectionV2",
                            "link": "47670",
                            "cityId": 0,
                            "restaurantUuid": "",
                            "restaurantParentId": "0",
                            "thirdPartyVendor": "",
                            "thirdPartyAddress": false,
                        },
                    }, {
                        "type": "carouselElement", "subtype": "image", "data": {
                            "bannerId": 181635,
                            "creativeId": "rng/md/carousel/production/yparhmxrby5lv0ubsel4",
                            "type": "restaurantCollectionV2",
                            "link": "56413",
                            "cityId": 0,
                            "restaurantUuid": "",
                            "restaurantParentId": "0",
                            "thirdPartyVendor": "",
                            "thirdPartyAddress": false,
                        },
                    }, {
                        "type": "carouselElement", "subtype": "image", "data": {
                            "bannerId": 607193,
                            "creativeId": "rng/md/carousel/production/s5ug2key6e2sptaxku5v",
                            "type": "restaurantCollectionV2",
                            "link": "56410",
                            "cityId": 0,
                            "restaurantUuid": "",
                            "restaurantParentId": "0",
                            "thirdPartyVendor": "",
                            "thirdPartyAddress": false,
                        },
                    }, {
                        "type": "carouselElement", "subtype": "image", "data": {
                            "bannerId": 607195,
                            "creativeId": "rng/md/carousel/production/ifi2lbzxeu1hvsqrsip3",
                            "type": "restaurantCollectionV2",
                            "link": "56421",
                            "cityId": 0,
                            "restaurantUuid": "",
                            "restaurantParentId": "0",
                            "thirdPartyVendor": "",
                            "thirdPartyAddress": false,
                        },
                    },],
                },
            }, "parentWidget": false,
        }, {
            "cardType": "carousel", "layoutAlignmentType": "VERTICAL", "data": {
                "type": "carousel", "subtype": "openFilter", "data": {
                    "cards": [{
                        "type": "carouselElement", "subtype": "image", "data": {
                            "bannerId": 181684,
                            "creativeId": "bkhjfipzydkoqncrxpyi",
                            "type": "restaurantCollectionV2",
                            "link": "11718",
                            "cityId": 0,
                            "restaurantUuid": "",
                            "restaurantParentId": "0",
                            "title": "Offers Near You",
                            "subtitle": "0 OPTIONS",
                            "restaurants": [],
                            "totalCount": 0,
                            "dwebOpenFilterTitle": "Offers Near You",
                            "dwebOpenFilterBgColor": "#FF0000",
                            "dwebOpenFilterSelectIcon": "eyperwsfhaoa5vktjtu4",
                            "dwebOpenFilterDeselectIcon": "urw8usdf4mk9aywd59gq",
                        },
                    }, {
                        "type": "carouselElement", "subtype": "image", "data": {
                            "bannerId": 181680,
                            "creativeId": "a3jqjjod5taken7dh1bs",
                            "type": "restaurantCollectionV2",
                            "link": "11721",
                            "cityId": 0,
                            "restaurantUuid": "",
                            "restaurantParentId": "0",
                            "title": "Veg Only",
                            "subtitle": "0 OPTIONS",
                            "restaurants": [],
                            "totalCount": 0,
                            "dwebOpenFilterTitle": "Vegetarian Options",
                            "dwebOpenFilterBgColor": "#FF0000",
                            "dwebOpenFilterSelectIcon": "qtjc8dzfexg72lug37a0",
                            "dwebOpenFilterDeselectIcon": "bm8bziikwyvwqsml1clm",
                        },
                    },],
                },
            }, "parentWidget": false,
        }, {
            "cardType": "seeAllRestaurants", "layoutAlignmentType": "VERTICAL", "data": {
                "type": "seeAllRestaurants", "data": {
                    "title": "SEE ALL", "totalOpenRestaurants": 1020, "cards": [{
                        "type": "restaurant", "data": {
                            "type": "F",
                            "id": "219834",
                            "name": "Everything@99",
                            "uuid": "f8da667b-138e-4edd-a7ee-05714ff8af89",
                            "city": "21",
                            "area": "New Textile Market",
                            "totalRatingsString": "1000+ ratings",
                            "cloudinaryImageId": "sgbxyxal011nfqfqkpze",
                            "cuisines": ["North Indian", "Biryani"],
                            "tags": [],
                            "costForTwo": 15000,
                            "costForTwoString": "₹150 FOR TWO",
                            "deliveryTime": 27,
                            "minDeliveryTime": 27,
                            "maxDeliveryTime": 27,
                            "slaString": "27 MINS",
                            "lastMileTravel": 5,
                            "slugs": {
                                "restaurant": "veg-factory-varachha-varachha", "city": "surat",
                            },
                            "cityState": "21",
                            "address": "DEPOT NO 7/166,  OPP JAIN DHARAMSHALA, STATION RD, SURAT",
                            "locality": "Railway Colony",
                            "parentId": 324447,
                            "unserviceable": false,
                            "veg": true,
                            "select": false,
                            "favorite": false,
                            "tradeCampaignHeaders": [],
                            "aggregatedDiscountInfo": {
                                "header": "50% off", "shortDescriptionList": [{
                                    "meta": "50% off on all orders",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                }, {
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "50% off on all orders",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                }, {
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "aggregatedDiscountInfoV2": {
                                "header": "50% OFF", "shortDescriptionList": [{
                                    "meta": "Free Delivery",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "50% off on all orders",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                }, {
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "ribbon": [{
                                "type": "PROMOTED",
                            },],
                            "chain": [],
                            "feeDetails": {
                                "fees": [], "totalFees": 0, "message": "", "title": "", "amount": "", "icon": "",
                            },
                            "availability": {
                                "opened": true, "nextOpenMessage": "", "nextCloseMessage": "",
                            },
                            "longDistanceEnabled": 0,
                            "rainMode": "NONE",
                            "thirdPartyAddress": false,
                            "thirdPartyVendor": "",
                            "adTrackingID": "cid=5801572~p=1~eid=00000186-9747-8a48-43d5-e8e900860136",
                            "badges": {
                                "imageBased": [], "textBased": [], "textExtendedBadges": [],
                            },
                            "lastMileTravelString": "5 kms",
                            "hasSurge": false,
                            "sla": {
                                "restaurantId": "219834",
                                "deliveryTime": 27,
                                "minDeliveryTime": 27,
                                "maxDeliveryTime": 27,
                                "lastMileTravel": 5,
                                "lastMileDistance": 0,
                                "serviceability": "SERVICEABLE",
                                "rainMode": "NONE",
                                "longDistance": "NOT_LONG_DISTANCE",
                                "preferentialService": false,
                                "iconType": "EMPTY",
                            },
                            "promoted": true,
                            "avgRating": "3.3",
                            "totalRatings": 1000,
                            "new": false,
                        }, "subtype": "basic",
                    }, {
                        "type": "restaurant", "data": {
                            "type": "F",
                            "id": "423422",
                            "name": "La Pino'z Pizza",
                            "uuid": "399cf620-043d-4176-8785-e3756a18213d",
                            "city": "21",
                            "area": "Magob",
                            "totalRatingsString": "1000+ ratings",
                            "cloudinaryImageId": "dmlu2z1eywppyxlhjkqq",
                            "cuisines": ["Pastas", "Pizzas"],
                            "tags": [],
                            "costForTwo": 30000,
                            "costForTwoString": "₹300 FOR TWO",
                            "deliveryTime": 22,
                            "minDeliveryTime": 22,
                            "maxDeliveryTime": 22,
                            "slaString": "22 MINS",
                            "lastMileTravel": 4.900000095367432,
                            "slugs": {
                                "restaurant": "la-pino’z-pizza-athwa-athwa", "city": "surat",
                            },
                            "cityState": "21",
                            "address": "61/62, 1st FLOOR, ABOVE HASTEE BAKERY, MAHENDRA PARK, AAI MATA CHOWK, PARVATPATIA, SURAT.",
                            "locality": "Mahendra Park",
                            "parentId": 4961,
                            "unserviceable": false,
                            "veg": true,
                            "select": false,
                            "favorite": false,
                            "tradeCampaignHeaders": [],
                            "aggregatedDiscountInfo": {
                                "header": "FREE DELIVERY", "shortDescriptionList": [{
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "aggregatedDiscountInfoV2": {
                                "header": "", "shortDescriptionList": [{
                                    "meta": "Free Delivery",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "ribbon": [{
                                "type": "PROMOTED",
                            },],
                            "chain": [],
                            "feeDetails": {
                                "fees": [], "totalFees": 0, "message": "", "title": "", "amount": "", "icon": "",
                            },
                            "availability": {
                                "opened": true, "nextOpenMessage": "", "nextCloseMessage": "",
                            },
                            "longDistanceEnabled": 0,
                            "rainMode": "NONE",
                            "thirdPartyAddress": false,
                            "thirdPartyVendor": "",
                            "adTrackingID": "cid=6009921~p=4~eid=00000186-9747-8a48-43d5-e8ea0086041a",
                            "badges": {
                                "imageBased": [], "textBased": [], "textExtendedBadges": [],
                            },
                            "lastMileTravelString": "4.9 kms",
                            "hasSurge": false,
                            "sla": {
                                "restaurantId": "423422",
                                "deliveryTime": 22,
                                "minDeliveryTime": 22,
                                "maxDeliveryTime": 22,
                                "lastMileTravel": 4.900000095367432,
                                "lastMileDistance": 0,
                                "serviceability": "SERVICEABLE",
                                "rainMode": "NONE",
                                "longDistance": "NOT_LONG_DISTANCE",
                                "preferentialService": false,
                                "iconType": "EMPTY",
                            },
                            "promoted": true,
                            "avgRating": "4.1",
                            "totalRatings": 1000,
                            "new": false,
                        }, "subtype": "basic",
                    }, {
                        "type": "restaurant", "data": {
                            "type": "F",
                            "id": "205488",
                            "name": "Jay Jalaram Thali",
                            "uuid": "14465b18-6e2c-42bf-b3ad-8a800d20da26",
                            "city": "21",
                            "area": "Gopipura",
                            "totalRatingsString": "10000+ ratings",
                            "cloudinaryImageId": "kih2hszmym1ygw2bokrl",
                            "cuisines": ["North Indian", "Biryani", "Punjabi", "Chinese"],
                            "tags": [],
                            "costForTwo": 13000,
                            "costForTwoString": "₹130 FOR TWO",
                            "deliveryTime": 19,
                            "minDeliveryTime": 19,
                            "maxDeliveryTime": 19,
                            "slaString": "19 MINS",
                            "lastMileTravel": 3.5,
                            "slugs": {
                                "restaurant": "jay-jalaram-thali-varachha-varachha", "city": "surat",
                            },
                            "cityState": "21",
                            "address": "1/3277, Behind Venus Chambers, Near Jain Bhojanshala, Kaji Maidan, Gopipura, Surat 395001",
                            "locality": "Kaji Maidan",
                            "parentId": 110113,
                            "unserviceable": false,
                            "veg": true,
                            "select": false,
                            "favorite": false,
                            "tradeCampaignHeaders": [],
                            "aggregatedDiscountInfo": {
                                "header": "60% off", "shortDescriptionList": [{
                                    "meta": "60% off | Use TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "60% off up to ₹120 | Use code TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "aggregatedDiscountInfoV2": {
                                "header": "60% OFF", "shortDescriptionList": [{
                                    "meta": "Use TRYNEW", "discountType": "Percentage", "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "60% off up to ₹120 | Use code TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "chain": [],
                            "feeDetails": {
                                "fees": [], "totalFees": 0, "message": "", "title": "", "amount": "", "icon": "",
                            },
                            "availability": {
                                "opened": true, "nextOpenMessage": "", "nextCloseMessage": "",
                            },
                            "longDistanceEnabled": 0,
                            "rainMode": "NONE",
                            "thirdPartyAddress": false,
                            "thirdPartyVendor": "",
                            "adTrackingID": "",
                            "badges": {
                                "imageBased": [], "textBased": [], "textExtendedBadges": [],
                            },
                            "lastMileTravelString": "3.5 kms",
                            "hasSurge": false,
                            "sla": {
                                "restaurantId": "205488",
                                "deliveryTime": 19,
                                "minDeliveryTime": 19,
                                "maxDeliveryTime": 19,
                                "lastMileTravel": 3.5,
                                "lastMileDistance": 0,
                                "serviceability": "SERVICEABLE",
                                "rainMode": "NONE",
                                "longDistance": "NOT_LONG_DISTANCE",
                                "preferentialService": false,
                                "iconType": "EMPTY",
                            },
                            "promoted": false,
                            "avgRating": "3.6",
                            "totalRatings": 10000,
                            "new": false,
                        }, "subtype": "basic",
                    }, {
                        "type": "restaurant", "data": {
                            "type": "F",
                            "id": "129855",
                            "name": "Vaishali Vadapav",
                            "uuid": "55127dca-b209-4c03-a3d3-763c5068cf1f",
                            "city": "21",
                            "area": "Althan Bhatar",
                            "totalRatingsString": "5000+ ratings",
                            "cloudinaryImageId": "v96xusgxtjhnbiwuwlfy",
                            "cuisines": ["Maharashtrian", "Street Food", "Chaat"],
                            "tags": [],
                            "costForTwo": 10000,
                            "costForTwoString": "₹100 FOR TWO",
                            "deliveryTime": 9,
                            "minDeliveryTime": 9,
                            "maxDeliveryTime": 9,
                            "slaString": "9 MINS",
                            "lastMileTravel": 0.800000011920929,
                            "slugs": {
                                "restaurant": "vaishali-vadapav-vesu-piplod", "city": "surat",
                            },
                            "cityState": "21",
                            "address": "3 Narayan Complex, Navrang Indu Compound, Sosyo Circle, khatodara, Vesu, Surat",
                            "locality": "Sosyo Circle",
                            "parentId": 8629,
                            "unserviceable": false,
                            "veg": true,
                            "select": false,
                            "favorite": false,
                            "tradeCampaignHeaders": [],
                            "aggregatedDiscountInfo": {
                                "header": "50% off", "shortDescriptionList": [{
                                    "meta": "50% off | Use TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "50% off up to ₹100 | Use code TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "aggregatedDiscountInfoV2": {
                                "header": "50% OFF", "shortDescriptionList": [{
                                    "meta": "Use TRYNEW", "discountType": "Percentage", "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "50% off up to ₹100 | Use code TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "chain": [],
                            "feeDetails": {
                                "fees": [], "totalFees": 0, "message": "", "title": "", "amount": "", "icon": "",
                            },
                            "availability": {
                                "opened": true, "nextOpenMessage": "", "nextCloseMessage": "",
                            },
                            "longDistanceEnabled": 0,
                            "rainMode": "NONE",
                            "thirdPartyAddress": false,
                            "thirdPartyVendor": "",
                            "adTrackingID": "",
                            "badges": {
                                "imageBased": [], "textBased": [], "textExtendedBadges": [],
                            },
                            "lastMileTravelString": "0.8 kms",
                            "hasSurge": false,
                            "sla": {
                                "restaurantId": "129855",
                                "deliveryTime": 9,
                                "minDeliveryTime": 9,
                                "maxDeliveryTime": 9,
                                "lastMileTravel": 0.800000011920929,
                                "lastMileDistance": 0,
                                "serviceability": "SERVICEABLE",
                                "rainMode": "NONE",
                                "longDistance": "NOT_LONG_DISTANCE",
                                "preferentialService": false,
                                "iconType": "EMPTY",
                            },
                            "promoted": false,
                            "avgRating": "4.0",
                            "totalRatings": 5000,
                            "new": false,
                        }, "subtype": "basic",
                    }, {
                        "type": "restaurant", "data": {
                            "type": "F",
                            "id": "401459",
                            "name": "Radhe Dhokla",
                            "uuid": "e25e1b1e-b22e-454b-b2d1-98f9c1d82533",
                            "city": "21",
                            "area": "Rustampura",
                            "totalRatingsString": "5000+ ratings",
                            "cloudinaryImageId": "27947ad42435b18fc7d1f127e841748a",
                            "cuisines": ["Chinese", "North Indian", "Biryani"],
                            "tags": [],
                            "costForTwo": 20000,
                            "costForTwoString": "₹200 FOR TWO",
                            "deliveryTime": 16,
                            "minDeliveryTime": 16,
                            "maxDeliveryTime": 16,
                            "slaString": "16 MINS",
                            "lastMileTravel": 2.5,
                            "slugs": {
                                "restaurant": "radhe-dhokla-athwa-athwa-2", "city": "surat",
                            },
                            "cityState": "21",
                            "address": "Singapuri wadi,Rustampura main road Behind 21st century Building, Ring Rd, Surat, Gujarat 395002",
                            "locality": "Ring Road",
                            "parentId": 4921,
                            "unserviceable": false,
                            "veg": true,
                            "select": false,
                            "favorite": false,
                            "tradeCampaignHeaders": [],
                            "aggregatedDiscountInfo": {
                                "header": "60% off", "shortDescriptionList": [{
                                    "meta": "60% off | Use TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "60% off up to ₹120 | Use code TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "aggregatedDiscountInfoV2": {
                                "header": "60% OFF", "shortDescriptionList": [{
                                    "meta": "Use TRYNEW", "discountType": "Percentage", "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "60% off up to ₹120 | Use code TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "chain": [],
                            "feeDetails": {
                                "fees": [], "totalFees": 0, "message": "", "title": "", "amount": "", "icon": "",
                            },
                            "availability": {
                                "opened": true, "nextOpenMessage": "", "nextCloseMessage": "",
                            },
                            "longDistanceEnabled": 0,
                            "rainMode": "NONE",
                            "thirdPartyAddress": false,
                            "thirdPartyVendor": "",
                            "adTrackingID": "",
                            "badges": {
                                "imageBased": [], "textBased": [], "textExtendedBadges": [],
                            },
                            "lastMileTravelString": "2.5 kms",
                            "hasSurge": false,
                            "sla": {
                                "restaurantId": "401459",
                                "deliveryTime": 16,
                                "minDeliveryTime": 16,
                                "maxDeliveryTime": 16,
                                "lastMileTravel": 2.5,
                                "lastMileDistance": 0,
                                "serviceability": "SERVICEABLE",
                                "rainMode": "NONE",
                                "longDistance": "NOT_LONG_DISTANCE",
                                "preferentialService": false,
                                "iconType": "EMPTY",
                            },
                            "promoted": false,
                            "avgRating": "4.4",
                            "totalRatings": 5000,
                            "new": false,
                        }, "subtype": "basic",
                    }, {
                        "type": "restaurant", "data": {
                            "type": "F",
                            "id": "93259",
                            "name": "Bismillah",
                            "uuid": "9abdbb44-22fd-4740-9bae-fd8a96d024ac",
                            "city": "21",
                            "area": "Chowk Bazaar",
                            "totalRatingsString": "10000+ ratings",
                            "cloudinaryImageId": "beiwfoxhdjv5tsmuo67k",
                            "cuisines": ["Desserts", "Ice Cream"],
                            "tags": [],
                            "costForTwo": 15000,
                            "costForTwoString": "₹150 FOR TWO",
                            "deliveryTime": 16,
                            "minDeliveryTime": 16,
                            "maxDeliveryTime": 16,
                            "slaString": "16 MINS",
                            "lastMileTravel": 4.199999809265137,
                            "slugs": {
                                "restaurant": "bismillah-juice-centre-athwa-athwa", "city": "surat",
                            },
                            "cityState": "21",
                            "address": "OPP. JUMMA MASJID, NEAR KAMAL GALI, CHOWK BAZAR, SURAT",
                            "locality": "Kamal Gali",
                            "parentId": 7587,
                            "unserviceable": false,
                            "veg": true,
                            "select": false,
                            "favorite": false,
                            "tradeCampaignHeaders": [],
                            "aggregatedDiscountInfo": {
                                "header": "60% off", "shortDescriptionList": [{
                                    "meta": "60% off | Use TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "60% off up to ₹120 | Use code TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "aggregatedDiscountInfoV2": {
                                "header": "60% OFF", "shortDescriptionList": [{
                                    "meta": "Use TRYNEW", "discountType": "Percentage", "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "60% off up to ₹120 | Use code TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "ribbon": [{
                                "type": "PROMOTED",
                            },],
                            "chain": [],
                            "feeDetails": {
                                "fees": [], "totalFees": 0, "message": "", "title": "", "amount": "", "icon": "",
                            },
                            "availability": {
                                "opened": true, "nextOpenMessage": "", "nextCloseMessage": "",
                            },
                            "longDistanceEnabled": 0,
                            "rainMode": "NONE",
                            "thirdPartyAddress": false,
                            "thirdPartyVendor": "",
                            "adTrackingID": "cid=5840537~p=7~eid=00000186-9747-8a48-43d5-e8eb00860737",
                            "badges": {
                                "imageBased": [], "textBased": [], "textExtendedBadges": [],
                            },
                            "lastMileTravelString": "4.1 kms",
                            "hasSurge": false,
                            "sla": {
                                "restaurantId": "93259",
                                "deliveryTime": 16,
                                "minDeliveryTime": 16,
                                "maxDeliveryTime": 16,
                                "lastMileTravel": 4.199999809265137,
                                "lastMileDistance": 0,
                                "serviceability": "SERVICEABLE",
                                "rainMode": "NONE",
                                "longDistance": "NOT_LONG_DISTANCE",
                                "preferentialService": false,
                                "iconType": "EMPTY",
                            },
                            "promoted": true,
                            "avgRating": "4.4",
                            "totalRatings": 10000,
                            "new": false,
                        }, "subtype": "basic",
                    }, {
                        "type": "restaurant", "data": {
                            "type": "F",
                            "id": "100721",
                            "name": "McDonald's",
                            "uuid": "64cad596-c1f0-4dd9-80e7-aee762237a74",
                            "city": "21",
                            "area": "Rustampura",
                            "totalRatingsString": "5000+ ratings",
                            "cloudinaryImageId": "7bb739d7f6ae8b4ce8ed590765dffd2f",
                            "cuisines": ["Burgers", "Beverages", "Cafe", "Desserts"],
                            "tags": [],
                            "costForTwo": 40000,
                            "costForTwoString": "₹400 FOR TWO",
                            "deliveryTime": 18,
                            "minDeliveryTime": 18,
                            "maxDeliveryTime": 18,
                            "slaString": "18 MINS",
                            "lastMileTravel": 2.4000000953674316,
                            "slugs": {
                                "restaurant": "mcdonalds-reliance-mall-varachha", "city": "surat",
                            },
                            "cityState": "21",
                            "address": "Hardcastle Restaurants Pvt Ltd,McDonalds Family Restaurants, RSM 09, RSM 24-26, Reliance Mega Mall, Udhana Darwaja, Opp. Passport Office, Ring Road, Surat - 394210, Gujarat.",
                            "locality": "Reliance Mall",
                            "parentId": 630,
                            "unserviceable": false,
                            "veg": false,
                            "select": false,
                            "favorite": false,
                            "tradeCampaignHeaders": [],
                            "aggregatedDiscountInfo": {
                                "header": "FREE DELIVERY", "shortDescriptionList": [{
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "aggregatedDiscountInfoV2": {
                                "header": "", "shortDescriptionList": [{
                                    "meta": "Free Delivery",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "chain": [],
                            "feeDetails": {
                                "fees": [], "totalFees": 0, "message": "", "title": "", "amount": "", "icon": "",
                            },
                            "availability": {
                                "opened": true, "nextOpenMessage": "", "nextCloseMessage": "",
                            },
                            "longDistanceEnabled": 0,
                            "rainMode": "NONE",
                            "thirdPartyAddress": false,
                            "thirdPartyVendor": "",
                            "adTrackingID": "",
                            "badges": {
                                "imageBased": [], "textBased": [], "textExtendedBadges": [],
                            },
                            "lastMileTravelString": "2.4 kms",
                            "hasSurge": false,
                            "sla": {
                                "restaurantId": "100721",
                                "deliveryTime": 18,
                                "minDeliveryTime": 18,
                                "maxDeliveryTime": 18,
                                "lastMileTravel": 2.4000000953674316,
                                "lastMileDistance": 0,
                                "serviceability": "SERVICEABLE",
                                "rainMode": "NONE",
                                "longDistance": "NOT_LONG_DISTANCE",
                                "preferentialService": false,
                                "iconType": "EMPTY",
                            },
                            "promoted": false,
                            "avgRating": "4.3",
                            "totalRatings": 5000,
                            "new": false,
                        }, "subtype": "basic",
                    }, {
                        "type": "restaurant", "data": {
                            "type": "F",
                            "id": "79331",
                            "name": "Sarvottam Restaurant",
                            "uuid": "0f2cb211-4d07-48ad-a7f0-82b405c84cb5",
                            "city": "21",
                            "area": "Udhna Gam",
                            "totalRatingsString": "10000+ ratings",
                            "cloudinaryImageId": "z4ldhn9m17fpxjksbcn1",
                            "cuisines": ["Chinese", "North Indian", "Ice Cream", "Pizzas", "Biryani",],
                            "tags": [],
                            "costForTwo": 30000,
                            "costForTwoString": "₹300 FOR TWO",
                            "deliveryTime": 14,
                            "minDeliveryTime": 14,
                            "maxDeliveryTime": 14,
                            "slaString": "14 MINS",
                            "lastMileTravel": 1.2000000476837158,
                            "slugs": {
                                "restaurant": "sarvottam-restaurant-varachha-varachha", "city": "surat",
                            },
                            "cityState": "21",
                            "address": "Shop No.1-16, First floor, Tulsi plaza complex, Udhna main Road, surat",
                            "locality": "Chandanvan Society",
                            "parentId": 178558,
                            "unserviceable": false,
                            "veg": true,
                            "select": false,
                            "favorite": false,
                            "tradeCampaignHeaders": [],
                            "aggregatedDiscountInfo": {
                                "header": "Rs 50 off", "shortDescriptionList": [{
                                    "meta": "15% off on all orders",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                }, {
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "15% off on all orders",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                }, {
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "aggregatedDiscountInfoV2": {
                                "header": "15% OFF", "shortDescriptionList": [{
                                    "meta": "Free Delivery",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "15% off on all orders",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                }, {
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "chain": [],
                            "feeDetails": {
                                "fees": [], "totalFees": 0, "message": "", "title": "", "amount": "", "icon": "",
                            },
                            "availability": {
                                "opened": true, "nextOpenMessage": "", "nextCloseMessage": "",
                            },
                            "longDistanceEnabled": 0,
                            "rainMode": "NONE",
                            "thirdPartyAddress": false,
                            "thirdPartyVendor": "",
                            "adTrackingID": "",
                            "badges": {
                                "imageBased": [], "textBased": [], "textExtendedBadges": [],
                            },
                            "lastMileTravelString": "1.2 kms",
                            "hasSurge": false,
                            "sla": {
                                "restaurantId": "79331",
                                "deliveryTime": 14,
                                "minDeliveryTime": 14,
                                "maxDeliveryTime": 14,
                                "lastMileTravel": 1.2000000476837158,
                                "lastMileDistance": 0,
                                "serviceability": "SERVICEABLE",
                                "rainMode": "NONE",
                                "longDistance": "NOT_LONG_DISTANCE",
                                "preferentialService": false,
                                "iconType": "EMPTY",
                            },
                            "promoted": false,
                            "avgRating": "4.1",
                            "totalRatings": 10000,
                            "new": false,
                        }, "subtype": "basic",
                    }, {
                        "type": "restaurant", "data": {
                            "type": "F",
                            "id": "93694",
                            "name": "New Janta Dairy",
                            "uuid": "4646d5ab-5240-4794-9f7a-b525726f10da",
                            "city": "21",
                            "area": "Althan Bhatar",
                            "totalRatingsString": "1000+ ratings",
                            "cloudinaryImageId": "mstdherryaqj9wj4qkyo",
                            "cuisines": ["Desserts"],
                            "tags": [],
                            "costForTwo": 20000,
                            "costForTwoString": "₹200 FOR TWO",
                            "deliveryTime": 12,
                            "minDeliveryTime": 12,
                            "maxDeliveryTime": 12,
                            "slaString": "12 MINS",
                            "lastMileTravel": 0.6000000238418579,
                            "slugs": {
                                "restaurant": "new-janta-dairy-piplod-piplod", "city": "surat",
                            },
                            "cityState": "21",
                            "address": "shop no 224, 1st floor, near manher dying udhna magdalla road, bhatiya complex surat",
                            "locality": "Sosyo Circle",
                            "parentId": 8623,
                            "unserviceable": false,
                            "veg": true,
                            "select": false,
                            "favorite": false,
                            "tradeCampaignHeaders": [],
                            "aggregatedDiscountInfo": {
                                "header": "FREE DELIVERY", "shortDescriptionList": [{
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "aggregatedDiscountInfoV2": {
                                "header": "", "shortDescriptionList": [{
                                    "meta": "Free Delivery",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "chain": [],
                            "feeDetails": {
                                "fees": [], "totalFees": 0, "message": "", "title": "", "amount": "", "icon": "",
                            },
                            "availability": {
                                "opened": true, "nextOpenMessage": "", "nextCloseMessage": "",
                            },
                            "longDistanceEnabled": 0,
                            "rainMode": "NONE",
                            "thirdPartyAddress": false,
                            "thirdPartyVendor": "",
                            "adTrackingID": "",
                            "badges": {
                                "imageBased": [], "textBased": [], "textExtendedBadges": [],
                            },
                            "lastMileTravelString": "0.6 kms",
                            "hasSurge": false,
                            "sla": {
                                "restaurantId": "93694",
                                "deliveryTime": 12,
                                "minDeliveryTime": 12,
                                "maxDeliveryTime": 12,
                                "lastMileTravel": 0.6000000238418579,
                                "lastMileDistance": 0,
                                "serviceability": "SERVICEABLE",
                                "rainMode": "NONE",
                                "longDistance": "NOT_LONG_DISTANCE",
                                "preferentialService": false,
                                "iconType": "EMPTY",
                            },
                            "promoted": false,
                            "avgRating": "4.1",
                            "totalRatings": 1000,
                            "new": false,
                        }, "subtype": "basic",
                    }, {
                        "type": "restaurant", "data": {
                            "type": "F",
                            "id": "352546",
                            "name": "Center Point -Gandhi Smruti",
                            "uuid": "40e80a9b-83de-4ce0-9aeb-1d2a591a263a",
                            "city": "21",
                            "area": "Nanpura",
                            "totalRatingsString": "10000+ ratings",
                            "cloudinaryImageId": "eha3nb1wqvs0p00kdeaw",
                            "cuisines": ["Chinese", "Burgers", "Pizzas"],
                            "tags": [],
                            "costForTwo": 20000,
                            "costForTwoString": "₹200 FOR TWO",
                            "deliveryTime": 19,
                            "minDeliveryTime": 19,
                            "maxDeliveryTime": 19,
                            "slaString": "19 MINS",
                            "lastMileTravel": 3,
                            "slugs": {
                                "restaurant": "center-point-fast-food-athwa-athwa-2", "city": "surat",
                            },
                            "cityState": "21",
                            "address": "S-49, KANAKNIDHI COMPLEX, OPP.GANDHI SMRUTI BHAVAN, TIMALIYAWAD, NANPURA, SURAT, Nanpura H.O, Surat Municipal Corporation, Surat Municipal Corporation, Gujarat",
                            "locality": "Timaliyawad",
                            "parentId": 56320,
                            "unserviceable": false,
                            "veg": true,
                            "select": false,
                            "favorite": false,
                            "tradeCampaignHeaders": [],
                            "aggregatedDiscountInfo": {
                                "header": "60% off", "shortDescriptionList": [{
                                    "meta": "60% off | Use TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "60% off up to ₹120 | Use code TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "aggregatedDiscountInfoV2": {
                                "header": "60% OFF", "shortDescriptionList": [{
                                    "meta": "Use TRYNEW", "discountType": "Percentage", "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "60% off up to ₹120 | Use code TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "chain": [],
                            "feeDetails": {
                                "fees": [], "totalFees": 0, "message": "", "title": "", "amount": "", "icon": "",
                            },
                            "availability": {
                                "opened": true, "nextOpenMessage": "", "nextCloseMessage": "",
                            },
                            "longDistanceEnabled": 0,
                            "rainMode": "NONE",
                            "thirdPartyAddress": false,
                            "thirdPartyVendor": "",
                            "adTrackingID": "",
                            "badges": {
                                "imageBased": [], "textBased": [], "textExtendedBadges": [],
                            },
                            "lastMileTravelString": "3 kms",
                            "hasSurge": false,
                            "sla": {
                                "restaurantId": "352546",
                                "deliveryTime": 19,
                                "minDeliveryTime": 19,
                                "maxDeliveryTime": 19,
                                "lastMileTravel": 3,
                                "lastMileDistance": 0,
                                "serviceability": "SERVICEABLE",
                                "rainMode": "NONE",
                                "longDistance": "NOT_LONG_DISTANCE",
                                "preferentialService": false,
                                "iconType": "EMPTY",
                            },
                            "promoted": false,
                            "avgRating": "4.0",
                            "totalRatings": 10000,
                            "new": false,
                        }, "subtype": "basic",
                    }, {
                        "type": "restaurant", "data": {
                            "type": "F",
                            "id": "65694",
                            "name": "Alpha Restaurant",
                            "uuid": "db8f0a7d-38a3-48e3-a1d3-18f541611e6a",
                            "city": "21",
                            "area": "Athwa",
                            "totalRatingsString": "5000+ ratings",
                            "cloudinaryImageId": "zdzduvnbeo8i3jr8xjnz",
                            "cuisines": ["Punjabi", "Chinese"],
                            "tags": [],
                            "costForTwo": 30000,
                            "costForTwoString": "₹300 FOR TWO",
                            "deliveryTime": 14,
                            "minDeliveryTime": 14,
                            "maxDeliveryTime": 14,
                            "slaString": "14 MINS",
                            "lastMileTravel": 2.299999952316284,
                            "slugs": {
                                "restaurant": "alpha-restaurant-bhatar-road-near-olympia-mall-athwa", "city": "surat",
                            },
                            "cityState": "21",
                            "address": "Shivshakti Shopping Center, Bhatar Road, Near Olympia Mall",
                            "locality": "Bhatar Road",
                            "parentId": 30581,
                            "unserviceable": false,
                            "veg": true,
                            "select": false,
                            "favorite": false,
                            "tradeCampaignHeaders": [],
                            "aggregatedDiscountInfo": {
                                "header": "20% off", "shortDescriptionList": [{
                                    "meta": "20% off | Use TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "20% off up to ₹50 | Use code TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "aggregatedDiscountInfoV2": {
                                "header": "20% OFF", "shortDescriptionList": [{
                                    "meta": "Use TRYNEW", "discountType": "Percentage", "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "20% off up to ₹50 | Use code TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "chain": [],
                            "feeDetails": {
                                "fees": [], "totalFees": 0, "message": "", "title": "", "amount": "", "icon": "",
                            },
                            "availability": {
                                "opened": true, "nextOpenMessage": "", "nextCloseMessage": "",
                            },
                            "longDistanceEnabled": 0,
                            "rainMode": "NONE",
                            "thirdPartyAddress": false,
                            "thirdPartyVendor": "",
                            "adTrackingID": "",
                            "badges": {
                                "imageBased": [], "textBased": [], "textExtendedBadges": [],
                            },
                            "lastMileTravelString": "2.2 kms",
                            "hasSurge": false,
                            "sla": {
                                "restaurantId": "65694",
                                "deliveryTime": 14,
                                "minDeliveryTime": 14,
                                "maxDeliveryTime": 14,
                                "lastMileTravel": 2.299999952316284,
                                "lastMileDistance": 0,
                                "serviceability": "SERVICEABLE",
                                "rainMode": "NONE",
                                "longDistance": "NOT_LONG_DISTANCE",
                                "preferentialService": false,
                                "iconType": "EMPTY",
                            },
                            "promoted": false,
                            "avgRating": "4.2",
                            "totalRatings": 5000,
                            "new": false,
                        }, "subtype": "basic",
                    }, {
                        "type": "restaurant", "data": {
                            "type": "F",
                            "id": "408520",
                            "name": "Bhandari Vishwas Tiffin Corner",
                            "uuid": "4c18c9bd-f602-4de8-8afc-f3c47256958e",
                            "city": "21",
                            "area": "Udhna Gam",
                            "totalRatingsString": "100+ ratings",
                            "cloudinaryImageId": "u3xxri5oxhznm8hceuxp",
                            "cuisines": ["Thalis", "North Indian"],
                            "tags": [],
                            "costForTwo": 20000,
                            "costForTwoString": "₹200 FOR TWO",
                            "deliveryTime": 19,
                            "minDeliveryTime": 19,
                            "maxDeliveryTime": 19,
                            "slaString": "19 MINS",
                            "lastMileTravel": 1.100000023841858,
                            "slugs": {
                                "restaurant": "bhandari-vishwas-tiffin-corner-athwa-athwa", "city": "surat",
                            },
                            "cityState": "21",
                            "address": "Plot no C 72, shiv krupa society amba nagar UM road behind unique hospital, Inderpura surat (395002)",
                            "locality": "Shiv Krupa Society",
                            "parentId": 242051,
                            "unserviceable": false,
                            "veg": false,
                            "select": false,
                            "favorite": false,
                            "tradeCampaignHeaders": [],
                            "aggregatedDiscountInfo": {
                                "header": "FREE DELIVERY", "shortDescriptionList": [{
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "aggregatedDiscountInfoV2": {
                                "header": "", "shortDescriptionList": [{
                                    "meta": "Free Delivery",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "chain": [],
                            "feeDetails": {
                                "fees": [], "totalFees": 0, "message": "", "title": "", "amount": "", "icon": "",
                            },
                            "availability": {
                                "opened": true, "nextOpenMessage": "", "nextCloseMessage": "",
                            },
                            "longDistanceEnabled": 0,
                            "rainMode": "NONE",
                            "thirdPartyAddress": false,
                            "thirdPartyVendor": "",
                            "adTrackingID": "",
                            "badges": {
                                "imageBased": [], "textBased": [], "textExtendedBadges": [],
                            },
                            "lastMileTravelString": "1.1 kms",
                            "hasSurge": false,
                            "sla": {
                                "restaurantId": "408520",
                                "deliveryTime": 19,
                                "minDeliveryTime": 19,
                                "maxDeliveryTime": 19,
                                "lastMileTravel": 1.100000023841858,
                                "lastMileDistance": 0,
                                "serviceability": "SERVICEABLE",
                                "rainMode": "NONE",
                                "longDistance": "NOT_LONG_DISTANCE",
                                "preferentialService": false,
                                "iconType": "EMPTY",
                            },
                            "promoted": false,
                            "avgRating": "3.8",
                            "totalRatings": 100,
                            "new": false,
                        }, "subtype": "basic",
                    }, {
                        "type": "restaurant", "data": {
                            "type": "F",
                            "id": "77744",
                            "name": "Famous Frankie",
                            "uuid": "10a9b620-fa41-40f5-9177-c101686cd13f",
                            "city": "21",
                            "area": "Athwa",
                            "totalRatingsString": "5000+ ratings",
                            "cloudinaryImageId": "noqecdgw1fy9z4rzonxd",
                            "cuisines": ["Street Food", "Fast Food", "North Indian", "Tandoor", "Chinese",],
                            "tags": [],
                            "costForTwo": 20000,
                            "costForTwoString": "₹200 FOR TWO",
                            "deliveryTime": 27,
                            "minDeliveryTime": 27,
                            "maxDeliveryTime": 27,
                            "slaString": "27 MINS",
                            "lastMileTravel": 5,
                            "slugs": {
                                "restaurant": "famous-franki-piplod-piplod", "city": "surat",
                            },
                            "cityState": "21",
                            "address": "218 citylights shopping centre. citylights main road near science centre, Citylight surat",
                            "locality": "Maharishi Dadhichi Road",
                            "parentId": 78451,
                            "unserviceable": false,
                            "veg": true,
                            "select": false,
                            "favorite": false,
                            "tradeCampaignHeaders": [],
                            "aggregatedDiscountInfo": {
                                "header": "60% off", "shortDescriptionList": [{
                                    "meta": "60% off | Use TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "60% off up to ₹120 | Use code TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "aggregatedDiscountInfoV2": {
                                "header": "60% OFF", "shortDescriptionList": [{
                                    "meta": "Use TRYNEW", "discountType": "Percentage", "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "60% off up to ₹120 | Use code TRYNEW",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "ribbon": [{
                                "type": "PROMOTED",
                            },],
                            "chain": [],
                            "feeDetails": {
                                "fees": [], "totalFees": 0, "message": "", "title": "", "amount": "", "icon": "",
                            },
                            "availability": {
                                "opened": true, "nextOpenMessage": "", "nextCloseMessage": "",
                            },
                            "longDistanceEnabled": 0,
                            "rainMode": "NONE",
                            "thirdPartyAddress": false,
                            "thirdPartyVendor": "",
                            "adTrackingID": "cid=5801639~p=16~eid=00000186-9747-8a48-43d5-e8ee00861016",
                            "badges": {
                                "imageBased": [], "textBased": [], "textExtendedBadges": [],
                            },
                            "lastMileTravelString": "5 kms",
                            "hasSurge": false,
                            "sla": {
                                "restaurantId": "77744",
                                "deliveryTime": 27,
                                "minDeliveryTime": 27,
                                "maxDeliveryTime": 27,
                                "lastMileTravel": 5,
                                "lastMileDistance": 0,
                                "serviceability": "SERVICEABLE",
                                "rainMode": "NONE",
                                "longDistance": "NOT_LONG_DISTANCE",
                                "preferentialService": false,
                                "iconType": "EMPTY",
                            },
                            "promoted": true,
                            "avgRating": "3.7",
                            "totalRatings": 5000,
                            "new": false,
                        }, "subtype": "basic",
                    }, {
                        "type": "restaurant", "data": {
                            "type": "F",
                            "id": "612570",
                            "name": "Satkar Restaurant",
                            "uuid": "ac899f69-c26a-4ef7-82ca-c71cd686467b",
                            "city": "21",
                            "area": "Udhana",
                            "totalRatingsString": "Too Few Ratings",
                            "cloudinaryImageId": "tvexgisocwix7erzwvgz",
                            "cuisines": ["North Indian", "Chinese"],
                            "tags": [],
                            "costForTwo": 30000,
                            "costForTwoString": "₹300 FOR TWO",
                            "deliveryTime": 24,
                            "minDeliveryTime": 24,
                            "maxDeliveryTime": 24,
                            "slaString": "24 MINS",
                            "lastMileTravel": 0.6000000238418579,
                            "slugs": {
                                "restaurant": "satkat-restaurent-athwa-athwa", "city": "surat",
                            },
                            "cityState": "21",
                            "address": "27/A, TP-1, FP-122, SHOP NO-325, 1ST FLOOR,  UDHNA STATION SHOPPING SHOP HOLDERS  CO OP SOC. LTD., NR. CITY CENTER, BAMROLI  ROAD, UDHNA,, Surat Municipal Corporation,  Gujarat-394210",
                            "locality": "Bamroli Road",
                            "parentId": 21553,
                            "unserviceable": false,
                            "veg": true,
                            "select": false,
                            "favorite": false,
                            "tradeCampaignHeaders": [],
                            "aggregatedDiscountInfo": {
                                "header": "5% off", "shortDescriptionList": [{
                                    "meta": "5% off on all orders",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                }, {
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "5% off on all orders",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                }, {
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "aggregatedDiscountInfoV2": {
                                "header": "5% OFF", "shortDescriptionList": [{
                                    "meta": "Free Delivery",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "5% off on all orders",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                }, {
                                    "meta": "FREE DELIVERY",
                                    "discountType": "FREE_DELIVERY",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "chain": [],
                            "feeDetails": {
                                "fees": [], "totalFees": 0, "message": "", "title": "", "amount": "", "icon": "",
                            },
                            "availability": {
                                "opened": true, "nextOpenMessage": "", "nextCloseMessage": "",
                            },
                            "longDistanceEnabled": 0,
                            "rainMode": "NONE",
                            "thirdPartyAddress": false,
                            "thirdPartyVendor": "",
                            "adTrackingID": "",
                            "badges": {
                                "imageBased": [], "textBased": [], "textExtendedBadges": [],
                            },
                            "lastMileTravelString": "0.6 kms",
                            "hasSurge": false,
                            "sla": {
                                "restaurantId": "612570",
                                "deliveryTime": 24,
                                "minDeliveryTime": 24,
                                "maxDeliveryTime": 24,
                                "lastMileTravel": 0.6000000238418579,
                                "lastMileDistance": 0,
                                "serviceability": "SERVICEABLE",
                                "rainMode": "NONE",
                                "longDistance": "NOT_LONG_DISTANCE",
                                "preferentialService": false,
                                "iconType": "EMPTY",
                            },
                            "promoted": false,
                            "avgRating": "--",
                            "totalRatings": 0,
                            "new": false,
                        }, "subtype": "basic",
                    }, {
                        "type": "restaurant", "data": {
                            "type": "F",
                            "id": "133179",
                            "name": "Ajay's",
                            "uuid": "838f60b8-fe6e-4237-b311-f3af4471945f",
                            "city": "21",
                            "area": "Udhna Gam",
                            "totalRatingsString": "100+ ratings",
                            "cloudinaryImageId": "bjt2cvc5afuyhj0shzjh",
                            "cuisines": ["Burgers"],
                            "tags": [],
                            "costForTwo": 15000,
                            "costForTwoString": "₹150 FOR TWO",
                            "deliveryTime": 16,
                            "minDeliveryTime": 16,
                            "maxDeliveryTime": 16,
                            "slaString": "16 MINS",
                            "lastMileTravel": 2,
                            "slugs": {
                                "restaurant": "ajays-udhna-parvat-patiya", "city": "surat",
                            },
                            "cityState": "21",
                            "address": "Bus Depot, Gurunagar, Udhana Main Rd, beside Bharat General Store, opp. Udhana, Udhna, Surat, Gujarat 394210",
                            "locality": "Udhna Teen Rasta",
                            "parentId": 6439,
                            "unserviceable": false,
                            "veg": true,
                            "select": false,
                            "favorite": false,
                            "tradeCampaignHeaders": [],
                            "aggregatedDiscountInfo": {
                                "header": "10% off", "shortDescriptionList": [{
                                    "meta": "10% off | Use JUMBO",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "10% off up to ₹100 on orders above ₹400 | Use code JUMBO",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "aggregatedDiscountInfoV2": {
                                "header": "10% OFF", "shortDescriptionList": [{
                                    "meta": "Use JUMBO", "discountType": "Percentage", "operationType": "RESTAURANT",
                                },], "descriptionList": [{
                                    "meta": "10% off up to ₹100 on orders above ₹400 | Use code JUMBO",
                                    "discountType": "Percentage",
                                    "operationType": "RESTAURANT",
                                },], "subHeader": "", "headerType": 0, "superFreedel": "",
                            },
                            "chain": [],
                            "feeDetails": {
                                "fees": [], "totalFees": 0, "message": "", "title": "", "amount": "", "icon": "",
                            },
                            "availability": {
                                "opened": true, "nextOpenMessage": "", "nextCloseMessage": "",
                            },
                            "longDistanceEnabled": 0,
                            "rainMode": "NONE",
                            "thirdPartyAddress": false,
                            "thirdPartyVendor": "",
                            "adTrackingID": "",
                            "badges": {
                                "imageBased": [], "textBased": [], "textExtendedBadges": [],
                            },
                            "lastMileTravelString": "2 kms",
                            "hasSurge": false,
                            "sla": {
                                "restaurantId": "133179",
                                "deliveryTime": 16,
                                "minDeliveryTime": 16,
                                "maxDeliveryTime": 16,
                                "lastMileTravel": 2,
                                "lastMileDistance": 0,
                                "serviceability": "SERVICEABLE",
                                "rainMode": "NONE",
                                "longDistance": "NOT_LONG_DISTANCE",
                                "preferentialService": false,
                                "iconType": "EMPTY",
                            },
                            "promoted": false,
                            "avgRating": "3.9",
                            "totalRatings": 100,
                            "new": false,
                        }, "subtype": "basic",
                    },], "totalRestaurants": 1020,
                }, "subtype": "personalized",
            }, "parentWidget": false,
        },], "nextPageFetch": 0,
    },
    "tid": "77ac26c0-337e-44c0-9b03-9fe552f14934",
    "sid": "5nq2812d-173e-41bc-821f-5bb8f0d480e9",
    "deviceId": "c1759119-53ed-de75-9af1-1ed7c70e124f",
    "csrfToken": "Y6Q5oT88rxjJ-eAmKLh9R1du44tHFPejwAfE1UjE",
};

export {RESTAURANT_DATA};
